[alias]
basic = "run --release --example basic"
ident = "run --release --example not_ident"
not-ident = "run --release --example not_ident"
char-to-byte = "run --release --example char_to_byte"
float-literals = "run --release --example float_literals"
float-literals-utf8-byte = "run --release --example float_literals_utf8_byte"
check-all = "test --release --all-targets"
